"""empty message

Revision ID: 003c20310306
Revises: 702f50cdb7d3
Create Date: 2025-02-28 17:59:55.703769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003c20310306'
down_revision = '702f50cdb7d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('transaction_type', sa.Text(), nullable=True))
        batch_op.drop_column('total_sales')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_sales', sa.INTEGER(), nullable=True))
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('customer_price')

    # ### end Alembic commands ###
