"""empty message

Revision ID: 0b4e8c8d8046
Revises: a3382e788a9c
Create Date: 2025-02-26 18:48:49.383114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4e8c8d8046'
down_revision = 'a3382e788a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.Column('work_time', sa.Text(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('company_cost', sa.Integer(), nullable=True),
    sa.Column('customer_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('indiv_works')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indiv_works',
    sa.Column('id', sa.TEXT(), nullable=False),
    sa.Column('site_id', sa.TEXT(), nullable=True),
    sa.Column('service_id', sa.TEXT(), nullable=True),
    sa.Column('work_time', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.Column('company_id', sa.TEXT(), nullable=True),
    sa.Column('memo', sa.TEXT(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=True),
    sa.Column('end_date', sa.DATE(), nullable=True),
    sa.Column('company_cost', sa.INTEGER(), nullable=True),
    sa.Column('customer_price', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('works')
    # ### end Alembic commands ###
