"""empty message

Revision ID: 0b746d94d38c
Revises: 9a010ad622d0
Create Date: 2025-04-26 23:19:18.087148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b746d94d38c'
down_revision = '9a010ad622d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_services',
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('fk_estimate_services_estimate_id_estimates')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_estimate_services_service_id_services'))
    )
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estimates_service_id_services', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.TEXT(), nullable=True))
        batch_op.create_foreign_key('fk_estimates_service_id_services', 'services', ['service_id'], ['id'])

    op.drop_table('estimate_services')
    # ### end Alembic commands ###
