"""empty message

Revision ID: 0cc1303e7a53
Revises: 660f4f5bd5dd
Create Date: 2025-06-12 02:08:51.955183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc1303e7a53'
down_revision = '660f4f5bd5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.Integer(), nullable=True))
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('category_code')

    # ### end Alembic commands ###
