"""empty message

Revision ID: 1a4e581894ec
Revises: 0b4e8c8d8046
Create Date: 2025-02-26 19:58:35.517230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a4e581894ec'
down_revision = '0b4e8c8d8046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Text(), nullable=True))
        batch_op.drop_column('services')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.TEXT(), nullable=True))
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
