"""empty message

Revision ID: 204c9028bd5e
Revises: 90811665ef72
Create Date: 2025-04-04 19:51:22.930194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '204c9028bd5e'
down_revision = '90811665ef72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('additional_cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('additional_cost')

    # ### end Alembic commands ###
