"""empty message

Revision ID: 315d154f2d72
Revises: 0cc1303e7a53
Create Date: 2025-06-13 01:40:46.994811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315d154f2d72'
down_revision = '0cc1303e7a53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.drop_column('category_code')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_size_small', sa.String(length=50), nullable=True))
        batch_op.alter_column(
            'room_size',
            existing_type=sa.Text(),
            type_=sa.Integer(),
            postgresql_using="room_size::integer"  # 🔥 핵심 부분
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('room_size',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('room_size_small')

    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
