"""empty message

Revision ID: 3c422c14a0b1
Revises: ec2cb4c827c4
Create Date: 2025-03-04 20:22:46.197356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c422c14a0b1'
down_revision = 'ec2cb4c827c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_price_change', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('customer_price_change')

    # ### end Alembic commands ###
