"""empty message

Revision ID: 3ce57b19eef0
Revises: 648915d117bc
Create Date: 2025-06-17 04:41:20.640990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ce57b19eef0'
down_revision = '648915d117bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.alter_column(
            'category_code',
            type_=sa.Integer(),
            postgresql_using='category_code::integer'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
