"""empty message

Revision ID: 441a7c619a06
Revises: af539762357c
Create Date: 2025-04-15 19:04:28.205765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '441a7c619a06'
down_revision = 'af539762357c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
