"""empty message

Revision ID: 525ad880eca1
Revises: 7c998855b6ad
Create Date: 2025-07-04 21:14:06.482636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '525ad880eca1'
down_revision = '7c998855b6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount3', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_column('discount3')
        batch_op.drop_column('discount2')
        batch_op.drop_column('discount1')

    # ### end Alembic commands ###
