"""empty message

Revision ID: 5494fc9254d6
Revises: 441a7c619a06
Create Date: 2025-04-15 19:17:54.230350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5494fc9254d6'
down_revision = '441a7c619a06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_sites_tax_id_taxes'), 'taxes', ['tax_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sites_tax_id_taxes'), type_='foreignkey')
        batch_op.drop_column('tax_id')

    # ### end Alembic commands ###
