"""empty message

Revision ID: 59974a60cdf3
Revises: 966125f5d292
Create Date: 2025-04-16 19:40:57.812506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59974a60cdf3'
down_revision = '966125f5d292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
