"""empty message

Revision ID: 60350f6cd8de
Revises: 00e87a33ae13
Create Date: 2025-03-01 13:14:31.482656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60350f6cd8de'
down_revision = '00e87a33ae13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archive', sa.Text(), nullable=True))
        batch_op.drop_column('archiving')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archiving', sa.TEXT(), nullable=True))
        batch_op.drop_column('archive')

    # ### end Alembic commands ###
