"""empty message

Revision ID: 62dcfedf3df2
Revises: df85b2c73f12
Create Date: 2025-06-17 04:13:54.132434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62dcfedf3df2'
down_revision = 'df85b2c73f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_code', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.drop_column('category_code')

    # ### end Alembic commands ###
