"""empty message

Revision ID: 648915d117bc
Revises: 62dcfedf3df2
Create Date: 2025-06-17 04:34:51.449696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648915d117bc'
down_revision = '62dcfedf3df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer(), nullable=True))
        batch_op.alter_column('service_id',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.alter_column('service_id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('code')

    # ### end Alembic commands ###
