"""서비스 카테고리 nullable 추가

Revision ID: 660f4f5bd5dd
Revises: 500f4b5a55d0
Create Date: 2025-06-11 11:13:04.829923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '660f4f5bd5dd'
down_revision = '500f4b5a55d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_categories_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_categories'))
    )
    op.drop_table('estimate_services')
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_service_options_category_id_service_categories'), 'service_categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_service_options_category_id_service_categories'), type_='foreignkey')
        batch_op.drop_column('category_id')

    op.create_table('estimate_services',
    sa.Column('estimate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('service_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('fk_estimate_services_estimate_id_estimates')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_estimate_services_service_id_services'))
    )
    op.drop_table('service_categories')
    # ### end Alembic commands ###
