"""package_price를 discounted_price로 변경

Revision ID: 677184ae006e
Revises: 0d9998b40ddc
Create Date: 2025-06-26 06:40:36.650633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '677184ae006e'
down_revision = '0d9998b40ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discounted_price', sa.Integer(), nullable=True))
        batch_op.drop_column('package_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_price', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('discounted_price')

    # ### end Alembic commands ###
