"""service_options에 package_price 컬럼 추가

Revision ID: 6c30b96d64aa
Revises: 677184ae006e
Create Date: 2025-06-26 07:26:29.036174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c30b96d64aa'
down_revision = '677184ae006e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.drop_column('package_price')

    # ### end Alembic commands ###
