"""empty message

Revision ID: 702f50cdb7d3
Revises: 1a4e581894ec
Create Date: 2025-02-27 11:34:51.400541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702f50cdb7d3'
down_revision = '1a4e581894ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modify_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_column('modify_date')

    # ### end Alembic commands ###
