"""empty message

Revision ID: 7c998855b6ad
Revises: 9e3848e2b2ce
Create Date: 2025-07-03 03:53:08.014579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c998855b6ad'
down_revision = '9e3848e2b2ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('category_code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('option_code', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_items', schema=None) as batch_op:
        batch_op.drop_column('option_code')
        batch_op.drop_column('category_code')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
