"""할인 테이블 생성

Revision ID: 81bc51b04312
Revises: 3ce57b19eef0
Create Date: 2025-06-25 10:57:43.644882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81bc51b04312'
down_revision = '3ce57b19eef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('discount_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('per_pyeong', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_discounts_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discounts'))
    )
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.alter_column('category_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('discounts')
    # ### end Alembic commands ###
