"""empty message

Revision ID: 90811665ef72
Revises: 05d18fefd7ad
Create Date: 2025-03-04 21:12:46.489056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90811665ef72'
down_revision = '05d18fefd7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('company_cost_base')
        batch_op.drop_column('customer_price_change')
        batch_op.drop_column('company_cost_change')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_cost_change', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('customer_price_change', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('company_cost_base', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
