"""empty message

Revision ID: 966125f5d292
Revises: 5494fc9254d6
Create Date: 2025-04-15 19:24:28.077064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '966125f5d292'
down_revision = '5494fc9254d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('statuses', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
