"""empty message

Revision ID: 9a010ad622d0
Revises: 9f4a15f83540
Create Date: 2025-04-25 18:05:28.452895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a010ad622d0'
down_revision = '9f4a15f83540'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimate_status_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_estimates_status_id_estimate_statuses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_estimates_estimate_status_id_estimate_statuses'), 'estimate_statuses', ['estimate_status_id'], ['id'])
        batch_op.drop_column('note')
        batch_op.drop_column('status_id')
        batch_op.drop_column('estimated_date')
        batch_op.drop_column('phone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('estimated_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('status_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('note', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_estimates_estimate_status_id_estimate_statuses'), type_='foreignkey')
        batch_op.create_foreign_key('fk_estimates_status_id_estimate_statuses', 'estimate_statuses', ['status_id'], ['id'])
        batch_op.drop_column('estimate_status_id')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('address')

    # ### end Alembic commands ###
