"""empty message

Revision ID: 9e3848e2b2ce
Revises: cfca977649b4
Create Date: 2025-07-03 01:57:25.817825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e3848e2b2ce'
down_revision = 'cfca977649b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('pyeong', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('small_room_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimates', schema=None) as batch_op:
        batch_op.drop_column('small_room_type')
        batch_op.drop_column('pyeong')
        batch_op.drop_column('room_type')

    # ### end Alembic commands ###
