"""empty message

Revision ID: 9f4a15f83540
Revises: b6c59b42e797
Create Date: 2025-04-25 10:56:42.664118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f4a15f83540'
down_revision = 'b6c59b42e797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_statuses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_estimate_statuses_estimate_id_estimates', type_='foreignkey')
        batch_op.drop_column('estimate_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_statuses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimate_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_estimate_statuses_estimate_id_estimates', 'estimates', ['estimate_id'], ['id'])

    # ### end Alembic commands ###
