"""empty message

Revision ID: a3382e788a9c
Revises: b9ba0c0eeab6
Create Date: 2025-02-26 16:38:52.174465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3382e788a9c'
down_revision = 'b9ba0c0eeab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('phone')

    # ### end Alembic commands ###
