"""empty message

Revision ID: af539762357c
Revises: fb59d3855f50
Create Date: 2025-04-15 18:48:17.019910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af539762357c'
down_revision = 'fb59d3855f50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_id', sa.Text(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_works_status_id_statuses'), 'statuses', ['status_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_works_status_id_statuses'), type_='foreignkey')
        batch_op.drop_column('status_id')

    # ### end Alembic commands ###
