"""service_options에서 package_price 컬럼 삭제

Revision ID: b3636c83cffd
Revises: 6c30b96d64aa
Create Date: 2025-06-26 07:31:13.141057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3636c83cffd'
down_revision = '6c30b96d64aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.drop_column('package_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_options', schema=None) as batch_op:
        batch_op.add_column(sa.Column('package_price', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
