"""empty message

Revision ID: b6c59b42e797
Revises: 59974a60cdf3
Create Date: 2025-04-25 10:49:45.189321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6c59b42e797'
down_revision = '59974a60cdf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estimate_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=True),
    sa.Column('estimate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], name=op.f('fk_estimate_statuses_estimate_id_estimates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimate_statuses'))
    )
    op.create_table('estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('estimated_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_estimates_service_id_services')),
    sa.ForeignKeyConstraint(['status_id'], ['estimate_statuses.id'], name=op.f('fk_estimates_status_id_estimate_statuses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_estimates'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_companies_service_id_services'), 'services', ['service_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_companies_service_id_services'), type_='foreignkey')

    op.drop_table('estimates')
    op.drop_table('estimate_statuses')
    # ### end Alembic commands ###
