"""empty message

Revision ID: cfca977649b4
Revises: 5718841892d2
Create Date: 2025-07-03 01:25:58.516605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfca977649b4'
down_revision = '5718841892d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_items', schema=None) as batch_op:
        batch_op.drop_column('quantity')
        batch_op.drop_column('pyeong')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estimate_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pyeong', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
