"""empty message

Revision ID: deb45d3eea23
Revises: 
Create Date: 2025-02-26 14:52:47.676097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'deb45d3eea23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('services', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('residence_type', sa.Text(), nullable=False),
    sa.Column('room_size', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('depositor', sa.Text(), nullable=False),
    sa.Column('customer_phone', sa.Text(), nullable=False),
    sa.Column('total_sales', sa.Integer(), nullable=False),
    sa.Column('contract_deposit', sa.Integer(), nullable=False),
    sa.Column('remaining_balance', sa.Integer(), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('indiv_works',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=True),
    sa.Column('service_id', sa.Text(), nullable=True),
    sa.Column('work_time', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('company_id', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('company_cost', sa.Integer(), nullable=True),
    sa.Column('customer_price', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indiv_works')
    op.drop_table('sites')
    op.drop_table('services')
    op.drop_table('companies')
    # ### end Alembic commands ###
