"""empty message

Revision ID: ec2367d9c655
Revises: deb45d3eea23
Create Date: 2025-02-26 15:04:05.970141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec2367d9c655'
down_revision = 'deb45d3eea23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('services',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('indiv_works', schema=None) as batch_op:
        batch_op.alter_column('work_time',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('residence_type',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('room_size',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('depositor',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('customer_phone',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('total_sales',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('contract_deposit',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('remaining_balance',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('contract_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('contract_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('remaining_balance',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('contract_deposit',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('total_sales',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('customer_phone',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('depositor',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('room_size',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('residence_type',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('indiv_works', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('details',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('work_time',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.alter_column('services',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
