"""empty message

Revision ID: fca96b1ea333
Revises: 3c422c14a0b1
Create Date: 2025-03-04 20:37:05.176832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca96b1ea333'
down_revision = '3c422c14a0b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_cost_change', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('company_cost_change')

    # ### end Alembic commands ###
